spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/showroom_2}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:yahya2004718}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=8080

jwt.secret=mySecretKeyForCarShowroomAppChangeThisInProductionItShouldBe64CharsLongAtLeast
jwt.expiration-ms=86400000